# Generated by Django 4.0.4 on 2022-06-12 02:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('synopsis', models.TextField()),
                ('tag', models.CharField(max_length=25)),
                ('rating', models.IntegerField()),
                ('poster', models.ImageField(upload_to='media')),
                ('release_year', models.IntegerField()),
                ('country', models.CharField(max_length=25)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('photo', models.ImageField(upload_to='media')),
            ],
            options={
                'ordering': ['-created'],
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(max_length=25)),
                ('title', models.CharField(blank=True, max_length=50)),
                ('text', models.TextField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.movie')),
            ],
            options={
                'ordering': ['-created'],
            },
        ),
    ]
