# Generated by Django 4.0.4 on 2022-06-12 19:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_remove_movie_genre_movie_genre'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='country',
        ),
    ]
