# Generated by Django 4.0.4 on 2022-06-20 10:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_alter_movie_genre'),
    ]

    operations = [
        migrations.CreateModel(
            name='Serie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Season',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField()),
                ('series', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.serie')),
            ],
        ),
        migrations.CreateModel(
            name='Episode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField()),
                ('synopsis', models.TextField()),
                ('rating', models.IntegerField()),
                ('poster', models.ImageField(upload_to='media')),
                ('release_year', models.IntegerField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('photo', models.ImageField(upload_to='media')),
                ('genre', models.ManyToManyField(to='base.genre')),
                ('industry', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='base.industry')),
                ('season', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='base.season')),
                ('series', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.serie')),
            ],
            options={
                'ordering': ['-created'],
            },
        ),
    ]
