# Generated by Django 4.0.4 on 2023-02-24 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_serie_season_episode'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='season',
            name='series',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='title',
        ),
        migrations.AddField(
            model_name='comment',
            name='rating',
            field=models.CharField(choices=[('poor', 'Poor'), ('meh', 'Meh'), ('mid', 'Mid'), ('decent', 'Decent'), ('rad', 'Rad')], max_length=50, null=True),
        ),
        migrations.RemoveField(
            model_name='movie',
            name='genre',
        ),
        migrations.AddField(
            model_name='movie',
            name='genre',
            field=models.CharField(choices=[('Thriller', 'Thriller'), ('Action', 'Action'), ('Drama', 'Drama'), ('Drama', 'Drama')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='movie',
            name='industry',
            field=models.CharField(choices=[('Hollywood', 'Hollywood'), ('Bollywood', 'Bollywood'), ('Korean', 'Korean'), ('African', 'African'), ('European', 'European')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='movie',
            name='rating',
            field=models.CharField(choices=[('poor', 'Poor'), ('meh', 'Meh'), ('mid', 'Mid'), ('decent', 'Decent'), ('rad', 'Rad')], max_length=10, null=True),
        ),
        migrations.DeleteModel(
            name='Episode',
        ),
        migrations.DeleteModel(
            name='Genre',
        ),
        migrations.DeleteModel(
            name='Industry',
        ),
        migrations.DeleteModel(
            name='Season',
        ),
        migrations.DeleteModel(
            name='Serie',
        ),
    ]
