# Generated by Django 4.0.4 on 2023-02-24 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_remove_season_series_remove_comment_title_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='photo',
        ),
        migrations.AddField(
            model_name='movie',
            name='trailer',
            field=models.FileField(null=True, upload_to='media'),
        ),
    ]
