# Generated by Django 4.0.4 on 2023-02-24 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0008_remove_movie_photo_movie_trailer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='rating',
            field=models.CharField(choices=[('Poor', 'Poor'), ('Meh', 'Meh'), ('Mid', 'Mid'), ('Decent', 'Decent'), ('Rad', 'Rad')], max_length=10, null=True),
        ),
    ]
