# Generated by Django 4.0.4 on 2023-02-24 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0009_alter_movie_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='status',
            field=models.CharField(choices=[('Released', 'Released'), ('Expected', 'Meh')], max_length=10, null=True),
        ),
    ]
