# Generated by Django 4.1.5 on 2023-03-16 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0012_movie_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='genre',
            field=models.CharField(choices=[('Thriller', 'Thriller'), ('Action', 'Action'), ('Comedy', 'Comedy'), ('Drama', 'Drama')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='movie',
            name='trailer',
            field=models.FileField(default='media/video.mp4', null=True, upload_to='media'),
        ),
    ]
